# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class EmailSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, objet=None, payload=None, frame=None, shape=None, logo=None):  # noqa: E501
        """EmailSchema - a model defined in OpenAPI

        :param email: The email of this EmailSchema.  # noqa: E501
        :type email: str
        :param objet: The objet of this EmailSchema.  # noqa: E501
        :type objet: str
        :param payload: The payload of this EmailSchema.  # noqa: E501
        :type payload: str
        :param frame: The frame of this EmailSchema.  # noqa: E501
        :type frame: str
        :param shape: The shape of this EmailSchema.  # noqa: E501
        :type shape: str
        :param logo: The logo of this EmailSchema.  # noqa: E501
        :type logo: str
        """
        self.openapi_types = {
            'email': str,
            'objet': str,
            'payload': str,
            'frame': str,
            'shape': str,
            'logo': str
        }

        self.attribute_map = {
            'email': 'email',
            'objet': 'objet',
            'payload': 'payload',
            'frame': 'frame',
            'shape': 'shape',
            'logo': 'logo'
        }

        self._email = email
        self._objet = objet
        self._payload = payload
        self._frame = frame
        self._shape = shape
        self._logo = logo

    @classmethod
    def from_dict(cls, dikt) -> 'EmailSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The emailSchema of this EmailSchema.  # noqa: E501
        :rtype: EmailSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this EmailSchema.


        :return: The email of this EmailSchema.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this EmailSchema.


        :param email: The email of this EmailSchema.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def objet(self):
        """Gets the objet of this EmailSchema.


        :return: The objet of this EmailSchema.
        :rtype: str
        """
        return self._objet

    @objet.setter
    def objet(self, objet):
        """Sets the objet of this EmailSchema.


        :param objet: The objet of this EmailSchema.
        :type objet: str
        """
        if objet is None:
            raise ValueError("Invalid value for `objet`, must not be `None`")  # noqa: E501

        self._objet = objet

    @property
    def payload(self):
        """Gets the payload of this EmailSchema.


        :return: The payload of this EmailSchema.
        :rtype: str
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this EmailSchema.


        :param payload: The payload of this EmailSchema.
        :type payload: str
        """
        if payload is None:
            raise ValueError("Invalid value for `payload`, must not be `None`")  # noqa: E501

        self._payload = payload

    @property
    def frame(self):
        """Gets the frame of this EmailSchema.


        :return: The frame of this EmailSchema.
        :rtype: str
        """
        return self._frame

    @frame.setter
    def frame(self, frame):
        """Sets the frame of this EmailSchema.


        :param frame: The frame of this EmailSchema.
        :type frame: str
        """

        self._frame = frame

    @property
    def shape(self):
        """Gets the shape of this EmailSchema.


        :return: The shape of this EmailSchema.
        :rtype: str
        """
        return self._shape

    @shape.setter
    def shape(self, shape):
        """Sets the shape of this EmailSchema.


        :param shape: The shape of this EmailSchema.
        :type shape: str
        """

        self._shape = shape

    @property
    def logo(self):
        """Gets the logo of this EmailSchema.


        :return: The logo of this EmailSchema.
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo):
        """Sets the logo of this EmailSchema.


        :param logo: The logo of this EmailSchema.
        :type logo: str
        """

        self._logo = logo
